# Missoes da Jornada do Novato (30 dias)

MISSOES = {
    1:  {"titulo": "Configure seus acessos", "desc": "E-mail, sistemas internos e cracha. Peca ajuda se travar!"},
    2:  {"titulo": "Descubra onde fica o cafe", "desc": "Explore o escritorio. Ache a cozinha, o banheiro e a saida de emergencia."},
    3:  {"titulo": "Apresente-se para 3 pessoas", "desc": "Nao precisa ser um discurso -- um 'oi, sou novo(a) aqui' ja vale."},
    4:  {"titulo": "Anote suas duvidas do dia", "desc": "Abra um bloco de notas e escreva tudo que nao entendeu. Sem vergonha!"},
    5:  {"titulo": "Descubra quem e seu ponto de apoio", "desc": "Identifique a pessoa que pode te ajudar no dia a dia (buddy/mentor)."},
    6:  {"titulo": "Entenda a rotina do time", "desc": "Pergunte: 'Como funciona o dia a dia aqui? Tem reuniao fixa?'"},
    7:  {"titulo": "Revise sua primeira semana", "desc": "Releia suas anotacoes. O que voce ja aprendeu? Celebre!"},
    8:  {"titulo": "Peca feedback pela primeira vez", "desc": "Pergunte ao seu gestor: 'Tem algo que posso melhorar?'"},
    9:  {"titulo": "Organize sua mesa/area de trabalho", "desc": "Arrume seu espaco fisico ou digital. Ambiente organizado = mente tranquila."},
    10: {"titulo": "Participe de uma reuniao sem medo", "desc": "Voce nao precisa falar muito. Ouvir com atencao ja e contribuir."},
    11: {"titulo": "Aprenda uma ferramenta do time", "desc": "Slack? Teams? Trello? Peca para alguem te mostrar o basico."},
    12: {"titulo": "Almoce com alguem diferente", "desc": "Conhecer pessoas de outras areas abre portas que voce nem imagina."},
    13: {"titulo": "Documente um processo que aprendeu", "desc": "Escreva com suas palavras algo que te ensinaram. Ajuda a fixar!"},
    14: {"titulo": "Celebre 2 semanas!", "desc": "Voce sobreviveu a metade do primeiro mes. Isso e incrivel!"},
    15: {"titulo": "Identifique algo que pode melhorar", "desc": "Nao precisa resolver -- so anotar ja mostra visao critica."},
    16: {"titulo": "Faca uma pergunta na reuniao", "desc": "Perguntar mostra interesse. Ninguem espera que voce saiba tudo."},
    17: {"titulo": "Agradeca alguem que te ajudou", "desc": "Um 'valeu pela forca' faz o dia de qualquer pessoa."},
    18: {"titulo": "Revise suas metas do mes", "desc": "Converse com seu gestor sobre o que esperam de voce ate o fim do mes."},
    19: {"titulo": "Teste resolver algo sozinho(a)", "desc": "Antes de perguntar, tente 15 min por conta. Depois peca ajuda sem culpa."},
    20: {"titulo": "Conheca outra area da empresa", "desc": "Entenda o que o time vizinho faz. Ajuda a ver o todo."},
    21: {"titulo": "Compartilhe algo que aprendeu", "desc": "Pode ser no chat do time. Ensinar e a melhor forma de aprender."},
    22: {"titulo": "Organize sua semana com antecedencia", "desc": "Anote na agenda o que pretende fazer amanha antes de sair hoje."},
    23: {"titulo": "Peca feedback de um colega", "desc": "Nao so do gestor -- colegas tem perspectivas valiosas."},
    24: {"titulo": "Resolva uma tarefa do inicio ao fim", "desc": "Escolha algo pequeno e entregue completo. A sensacao e otima!"},
    25: {"titulo": "Reflita: o que me surpreendeu?", "desc": "O que foi diferente do que voce esperava? Anote."},
    26: {"titulo": "Proponha uma ideia simples", "desc": "Pode ser pequena. Mostrar iniciativa conta muito."},
    27: {"titulo": "Prepare-se para a conversa de 1 mes", "desc": "Liste o que aprendeu, o que ainda tem duvida e o que quer aprender."},
    28: {"titulo": "Releia todas as suas anotacoes", "desc": "Veja o quanto voce evoluiu em menos de um mes!"},
    29: {"titulo": "Agradeca ao time", "desc": "Uma mensagem simples: 'Obrigado(a) por me receberem tao bem.'"},
    30: {"titulo": "Missao final: Auto-avaliacao", "desc": "Escreva 3 coisas que voce faz melhor hoje do que no Dia 1. Parabens!"},
}
